import React from 'react';
import { Edit, CheckCircle, Play, Eye } from 'lucide-react';
import axios from 'axios';

const QuizList = ({ quizzes, onEdit, onRefresh, onView }) => {

  const handleApprove = async (id) => {
    if (!window.confirm('Are you sure you want to approve this quiz?')) return;
    try {
      await axios.put(`http://localhost:5000/api/admin/quizzes/${id}/approve`);
      onRefresh();
    } catch (err) {
      alert(err.response?.data?.error || 'Approval failed');
    }
  };

  const handleActivate = async (quiz) => {
    const defaultDate = quiz.activeDate ? new Date(quiz.activeDate).toISOString().split('T')[0] : new Date().toISOString().split('T')[0];
    const dateStr = prompt(`Activate this quiz for which date? \nTo be visible to users on:`, defaultDate);
    if (!dateStr) return;
    try {
      await axios.put(`http://localhost:5000/api/admin/quizzes/${quiz._id}/activate`, { activeDate: dateStr });
      onRefresh();
    } catch (err) {
      alert(err.response?.data?.error || 'Activation failed');
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'DRAFT': return 'var(--text-secondary)';
      case 'APPROVED': return 'var(--accent-primary)';
      case 'ACTIVE': return 'var(--success)';
      case 'ARCHIVED': return 'var(--error)';
      default: return 'gray';
    }
  };

  return (
    <div className="glass-card" style={{ padding: '20px' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
        <thead>
          <tr style={{ borderBottom: '1px solid var(--glass-border)', color: 'var(--text-secondary)' }}>
            <th style={{ padding: '15px' }}>Status</th>
            <th style={{ padding: '15px' }}>Title</th>
            <th style={{ padding: '15px' }}>Generated By</th>
            <th style={{ padding: '15px' }}>Active Date</th>
            <th style={{ padding: '15px' }}>Actions</th>
          </tr>
        </thead>
        <tbody>
          {quizzes.map((quiz) => (
            <tr key={quiz._id} style={{ borderBottom: '1px solid var(--glass-border)' }}>
              <td style={{ padding: '15px' }}>
                <span style={{ 
                  padding: '4px 10px', 
                  borderRadius: '20px', 
                  fontSize: '0.8rem',
                  background: `rgba(255,255,255,0.05)`,
                  color: getStatusColor(quiz.status),
                  border: `1px solid ${getStatusColor(quiz.status)}`
                }}>
                  {quiz.status}
                </span>
              </td>
              <td style={{ padding: '15px' }}>{quiz.title}</td>
              <td style={{ padding: '15px' }}>
                {quiz.generatedBy === 'AI' ? (
                  <span style={{ color: 'var(--accent-secondary)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                     🤖 AI
                  </span>
                ) : 'Manual'}
              </td>
              <td style={{ padding: '15px' }}>
                 {quiz.activeDate ? new Date(quiz.activeDate).toLocaleDateString() : '-'}
              </td>
              <td style={{ padding: '15px', display: 'flex', gap: '10px' }}>
                <button 
                    onClick={() => onView(quiz)} 
                    title="View Details" 
                    style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer' }}
                >
                    <Eye size={18} />
                </button>

                {quiz.status !== 'ACTIVE' && quiz.status !== 'ARCHIVED' && (
                  <button onClick={() => onEdit(quiz)} title="Edit" style={{ background: 'none', border: 'none', color: 'var(--text-primary)', cursor: 'pointer' }}>
                    <Edit size={18} />
                  </button>
                )}
                
                {quiz.status === 'DRAFT' && (
                  <button onClick={() => handleApprove(quiz._id)} title="Approve" style={{ background: 'none', border: 'none', color: 'var(--success)', cursor: 'pointer' }}>
                    <CheckCircle size={18} />
                  </button>
                )}

                {(quiz.status === 'DRAFT' || quiz.status === 'APPROVED') && (
                  <button 
                    onClick={() => handleActivate(quiz)} 
                    title={quiz.status === 'DRAFT' ? "Approve & Activate" : "Activate"}
                    style={{ background: 'none', border: 'none', color: 'var(--accent-primary)', cursor: 'pointer' }}
                  >
                    <Play size={18} />
                  </button>
                )}
              </td>
            </tr>
          ))}
          {quizzes.length === 0 && (
            <tr>
              <td colSpan="5" style={{ padding: '20px', textAlign: 'center', color: 'var(--text-secondary)' }}>
                No quizzes found.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
};

export default QuizList;
